# Generated by Django 3.2.25 on 2026-04-27 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BizInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bk_biz_id', models.IntegerField(unique=True)),
                ('bk_biz_name', models.CharField(max_length=50)),
            ],
        ),
    ]
